media:
  input: img
  output: img

content:
  # -------------------------------------------------
  # Blog Posts (Beautiful Jekyll kompatibel)
  # -------------------------------------------------
  - name: posts
    label: Beiträge
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{slug}.md"

    view:
      fields: [ title, date, tags ]
      sort: [ date, desc ]

    fields:
      # -------- Pflichtfelder --------
      - name: layout
        type: string
        hidden: true
        default: post

      - name: title
        label: Titel
        type: string
        required: true

      - name: subtitle
        label: Untertitel
        type: string

      - name: date, label: Date, type: date

      # -------- Metadaten --------
      - name: author
        label: Autor
        type: string

      - name: tags
        label: Tags
        type: list
        description: "Wird als YAML-Array gespeichert: [tag1, tag2]"

      - name: comments
        label: Kommentare aktiv
        type: boolean
        default: true

      - name: mathjax
        label: MathJax aktivieren
        type: boolean
        default: false

      # -------- GitHub Features --------
      - name: gh-repo
        label: GitHub Repository
        type: string
        description: "z.B. daattali/beautiful-jekyll"

      - name: gh-badge
        label: GitHub Badges
        type: list
        description: "Mögliche Werte: star, fork, follow"

      # -------- Bilder --------
      - name: image
        label: Artikelbild (Header)
        type: image
        description: "Wird als image: /img/xyz.jpg gesetzt"

      - name: share-img
        label: Social Share Image
        type: image
        description: "OpenGraph / Twitter Card"

      # -------- Inhalt --------
      - name: body
        label: Inhalt
        type: rich-text
        required: true
