# pages-cms Konfiguration für Beautiful Jekyll
backend:
  name: github
  repo: thahipster/thahipster.github.io
  branch: master   # ggf. auf 'master' ändern

media_folder: "img"
public_folder: "/img"

site_url: https://thahipster.github.io

collections:
  - name: "posts"
    label: "Blogposts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Untertitel", name: "subtitle", widget: "string", required: false }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string", required: false }
      - { label: "Kategorien", name: "categories", widget: "list", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Header-Bild", name: "image", widget: "image", required: false }
      - { label: "Inhalt", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Seiten"
    files:
      - file: "about.md"
        label: "Über mich"
        name: "about"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }
